### ISSUE TITLE
Fail to upgrade Org Policy with AzSK from 4.4.0 to 4.10.0

### ISSUE THREAD

**Issue by EvgeniaMartynova** [azsk/DevOpsKit#1074]
## Description</br>
Fail to upgrade Org Policy with AzSK from 4.4.0 to 4.10.0
## Steps to reproduce
1. Update locally AzSK module to 4.10.0
2. Run the following command to upgrade the Org Policy with a new version of AzSK
```PowerShell
Update-AzSKOrganizationPolicy -SubscriptionId SubscriptionId `
   -OrgName 'Contoso-IT' `           
   -ResourceGroupName 'Contoso-IT-RG' `
   -StorageAccountName 'contosoitsa' `
   -PolicyFolderPath 'D:\\ContosoPolicies' -OverrideBaseConfig OrgAzSKVersion
```

The command executed successfully, the local file AzSK.Pre.json is updated with version 4.10.0
However 

## Expected behavior</br> 
Org Policy is upgraded to version 4.10.0
## Actual behavior</br>
In the end of the execution the log output of the command is saying 'Searching for an ealier version. Uninstalling 4.10.0'
As a result the Org Policy is not upgrading and staying 4.4.0

**Comment by ganesh-msft** [comment]
Can you provide the complete output of Update-AzSKOrganizationPolicy command?

**Comment by EvgeniaMartynova** [comment]
PowerShellOutput.LOG
`================================================================================
AzSK Version: 4.10.0 
================================================================================
Method Name: Update-AzSKOrganizationPolicy (UOP)
Input Parameters: 
Name                        Alias Value                               
----                        ----- -----                               
SubscriptionId              s     <sub_id>
OrgName                     oname <org_name>                          
ResourceGroupName           rgn   <rg_name>                  
StorageAccountName          san   <storage_account_name>                     
PolicyFolderPath            pfp   C:\LNSPolicies1                     
OverrideBaseConfig          oride OrgAzSKVersion                      
MonitoringDashboardLocation mdl   EastUS 

You can also use: uop -s "sub_id" -oname "<org_name>" -rgn "<rg_name>" -san "<storage_account_name>" -pfp "C:\LNSPolicies1" -oride "OrgAzSKVersion" -mdl "EastUS"  
================================================================================
Running AzSK cmdlet using ***<org_name>*** policy...
This command will perform 2 important operations. It will:
   [1] Upload policies to the policy server 
   [2] Generate an org-specific installer ('iwr' command) for your org 
--------------------------------------------------------------------------------
[1] Uploading policy files to policy server...
Uploading [1] file(s) to container [installer]...
All files have been uploaded to container [installer]
Uploading [3] file(s) to container [policies]...
All files have been uploaded to container [policies]
Uploading [46] file(s) to container [policies]...
All files have been uploaded to container [policies]
All policy files have been uploaded successfully.
--------------------------------------------------------------------------------
[2] Generating an org-specific installer ('iwr' command) for your org...
iwr 'https://<storage_account_name>.blob.core.windows.net/installer/AzSK-EasyInstaller.ps1' -UseBasicParsing | iex
Installer generated successfully. Run the 'iwr' command above to install Organization specific version.
IMPORTANT: Make sure anyone in your org who needs to scan according to your policies uses the above 'iwr' command to install AzSK. (They should not use 'install-module AzSK' directly. Anyone using an incorrect setup will not get your custom '<org_name>' policy when they run any AzSK cmdlet.)
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
 
The setup has been completed and policies have been copied to [C:\LNSPolicies1].
If you happen to lose/forget them, you can always re-download using Get-AzSKOrganizationPolicyStatus with -DownloadPolicy parameter.
 
Note: This is a basic setup and uses a public access blob for storing your org's installer. Once you have richer org policies, consider using a location/end-point protected by your tenant authentication.
================================================================================
Logs have been exported to: 'C:\Users\evma\AppData\Local\Microsoft\AzSKLogs\<sub_name>\20200619_173833_UOP'
================================================================================`

iwr command output log:
` iwr 'https://azsktomtomlnssa.blob.core.windows.net/installer/AzSK-EasyInstaller.ps1' -UseBasicPa
rsing | iex
>>

Checking Prerequisites...
Prerequisite Passed: PowerShell version needs to be 5.0 or above.
Prerequisite Passed: PowerShell Nuget PackageProvider version needs to be 2.8.5.208 or above.
Checking if a previous version of AzSK is present on your machine...
Found AzSK version 4.10.0 . Uninstalling it...
Completed uninstallation.
Installing AzSK version 4.4.0 . This may take a few minutes...

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its
InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from
'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"):

`

**Comment by EvgeniaMartynova** [comment]
I had a great screen sharing session today with AzSK engineers.
A mistake from my side was that I didn't import the updated module into the PowerShell session.
Here are the PowerShell commands which we executed to perform the actual Org Policy update with AzSK 4.10.0:

`Get-Module -ListAvailable AzSK
Install-Module AzSK -Scope CurrentUser -AllowClobber -Force
IPMO AzSK
Update-AzSKOrganizationPolicy -SubscriptionId sub_id `
     -OrgName "orgname" -ResourceGroupName "rg_name" `
      -StorageAccountName "storage_account_name" `
      -PolicyFolderPath "policy_folder_path" `
      -OverrideBaseConfig OrgAzSKVersion

iwr 'https://storage_account_name.blob.core.windows.net/installer/AzSK-EasyInstaller.ps1' -UseBasicParsing | iex
 Get-AzSKOrganizationPolicyStatus -SubscriptionId sub_id `
 -OrgName "org_name" -ResourceGroupName "rg_name" `
 -StorageAccountName "storage_account_name" `
 -PolicyFolderPath "policy_folder_name" `
 -DownloadPolicy`
