### ISSUE TITLE
Azure_AppService_Audit_Enable_Logging_and_Monitoring fails when two Diagnostics settings are configured, but only one has all required logs enabled

### ISSUE THREAD

**Issue by wirelessy** [azsk/DevOpsKit#1148]
## Title</br>
WebApp "Azure_AppService_Audit_Enable_Logging_and_Monitoring" AzSK check fails when two Diagnostics settings are configured, but only one has all required logs enabled

## Description</br>
08/11/2020 12:39:55-Checking: [AppService]-[Auditing and Monitoring must be enabled for App Service] for resource [WebAppResource]
All configurations of diagnostics logs for resource WebAppResource are not enabled
@{
    "DetailedErrorLoggingEnabled" = $True;
    "HttpLoggingEnabled" = $False;
    "RequestTracingEnabled" = $True
}

However, this WebApp has two diagnostic settings. One, which logs all available data to a Log Analytics workspace.
Another one, which only logs some tracing data to a developers storage account, as seen in the above config.

Since there is a config available, which is logging all necessary data, this control should not fail.

## Steps to reproduce
Configure a Web App with two Diagnostic Settings.

One that logs ALL categories.
Another one that logs only a subset of e.g. DetailedErrorLogging and RequestTracing.

Then AzSK scan it.

## Expected behavior</br> 
The control does not fail.

## Actual behavior</br>
The control fails, because it is ignoring the second Diagnostic setting.
![2020-08-12 09 50 58 portal azure com 0a9ddf186271](https://user-images.githubusercontent.com/54665179/89989714-9e1fd680-dc81-11ea-8178-b1219f912834.png)
![2020-08-12 09 51 11 portal azure com 2893dd3889b5](https://user-images.githubusercontent.com/54665179/89989716-9eb86d00-dc81-11ea-9572-5ce32474dfa1.png)
![2020-08-12 09 51 32 portal azure com 5a1fd2a831cb](https://user-images.githubusercontent.com/54665179/89989718-9f510380-dc81-11ea-88dd-d930af4f1072.png)

**Comment by v-himkam** [comment]
The control Azure_AppService_Audit_Enable_Logging_and_Monitoring checks for HTTP Logging, DetailedError Logging, and Request Tracing, all three must be enabled for App Service.

For Enabling all three on AppService having Standard mode, follow the below steps:
1.)	On the Azure portal, open the AppService Logs section for your AppService. Then, select an option for Web server logging (i.e. HTTPLogging).
1.1)	If the Storage option is selected then you need to configure a container of a storage account with AppService.
1.1.1)	You can select the existing storage account. (If already present)
1.1.2)	You can create a new storage account.
1.1.3) After making the storage account or selecting the existing one, you need to add a container in it.
1.2) File System can also be selected for HTTP Logging.
2.)  Give the no. of days for the Retention period and Select the “ON” button for Detailed error messages and Failed Request Tracing.
3.) Auditing for logging and monitoring for AppService is enabled now.

For Enabling all three on AppService having Basic mode, follow the below steps:
1.	Open PowerShell ISE on your local machine or use cloud shell on Azure portal.
2.	Run command 
'Set-AzWebApp -Name '<WebAppName>' -ResourceGroupName '<RGName>' -DetailedErrorLoggingEnabled $true -HttpLoggingEnabled $true -RequestTracingEnabled $true'

Note: You can use the above command in case of AppService having Standard mode.

**Comment by wirelessy** [comment]
Your comment is referring a $null amount to the original issue.
No resolve has been happened, no confirm, no deny.
Why do you close the issue? This still persists, and your described procedure is NOT tackling the described issue.
