### ISSUE TITLE
Module not catalog signed

### ISSUE THREAD

**Issue by tsunami28** [azsk/DevOpsKit#1237]
## Title</br>
Module not catalog signed
## Description</br>
The version '1.1.2' of the module 'Az.AnalysisServices' being installed is not catalog signed.
## Steps to reproduce

# First time installation
```PowerShell
Install-Module AzSK -Scope CurrentUser -AllowClobber
```
## Expected behavior</br> 
Successful installation 

## Actual behavior</br>
Install-Package: C:\program files\powershell\7\Modules\PowerShellGet\PSModule.psm1:9709:34
Line |
9709 |  … talledPackages = PackageManagement\Install-Package @PSBoundParameters
     |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The version '1.1.2' of the module 'Az.AnalysisServices' being installed is not catalog signed. Ensure that the version '1.1.2' of the module 'Az.AnalysisServices' has the catalog file 'Az.AnalysisServices.cat' and signed with the same publisher
     | 'CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US' as the previously-installed module 'Az.AnalysisServices' with version '1.1.4' under the directory 'C:\Program
     | Files\WindowsPowerShell\Modules\Az.AnalysisServices\1.1.4'. If you still want to install or update, use -SkipPublisherCheck parameter.

**Comment by v-soukum** [comment]
I tried it multiple times, but every time it got successfully installed. It seems that you have a different version of Az modules installed on your machine. You may need to use -AllowClobber and -Force options with the Install-Module command

`Install-Module AzSK -Scope CurrentUser -AllowClobber -Force`

Also, ensure that you are using PowerShell 5.0 or higher. Refer to this [document](https://github.com/azsk/DevOpsKit-docs/blob/master/00a-Setup/Readme.md) for more details.
