### ISSUE TITLE
Support for Azure Blueprints?

### ISSUE THREAD

**Issue by kkazala** [azsk/DevOpsKit#1367]
## Description</br>
It's not an issue :)
Are there plans to support AZ Blueprints and if yes, what it the roadmap?

thank you in advance for the answer  :)

**Comment by ritika-msft** [comment]
As of now we have no support for AZ Blueprint. 

Having said that, I would like to let you know that the PowerShell-based DevOpsKit (AzSK) is being sunset. We plan to stop further work/support after FY21. If you are just getting started, we’d suggest you consider using the more scalable tenant scanning solution as described [here](url) .

We have stopped active development of both the CICD extensions (AzSK SVTs and ARM Template Checker). We’ll only do the absolutely necessary fixes (if any) through the remainder of FY21.
Extensions may remain in the gallery beyond that but without any active maintenance.

As we migrate to AzTS and eliminate dependencies on AzSK, we continue to evaluate all possibilities of  having as many AzSK capabilities as possible/relevant retained in the new solution. Accordingly, if there is any further update regarding the CICD extensions, we’ll share it via the GitHub notice.
