### ISSUE TITLE
Cannot deploy Install-AzSKOrganizationPolicy with App insights location set...

### ISSUE THREAD

**Issue by Stoffe** [azsk/DevOpsKit#195]
## Title</br>
Cannot deploy Install-AzSKOrganizationPolicy with App insights location set...

## Description </br>
Setting the -AppInsightLocation northeurope or westeurope will result in an error, </br>
Install-AzSKOrganizationPolicy : Parameter set cannot be resolved using the specified named parameters.</br>

## Steps to reproduce
Call Install-AzSKOrganizationPolicy with a -AppInsightLocation of north or west europe.

```PowerShell
Install-AzSKOrganizationPolicy -SubscriptionId <SUBID> -OrgName "<NAME>" -DepartmentName "<DEP>" -PolicyFolderPath "<C: PATH>" -ResourceGroupLocation westeurope -AppInsightLocation westeurope -ResourceGroupName "<NAME>" -AppInsightName "<NAME>"
```
## Expected behavior</br> 
Should set AppInsights location to the north or west europe.

## Actual behavior</br>
Error, if this parameter is left out, the app insights will deploy to east US, which is not compliant for us.

**Comment by VishalHaibatpure** [comment]
Please use below parameter set for customized setup for Org Policy. 

Install-AzSKOrganizationPolicy -SubscriptionId <SUBID> -OrgName "<ORGNAME>" -StorageAccountName "<storagename>" -ResourceGroupLocation westeurope -AppInsightLocation westeurope -MonitoringDashboardLocation westeurope -ResourceGroupName "<NAME>" -AppInsightName "<NAME>" -PolicyFolderPath "<C: PATH>"

**Comment by Stoffe** [comment]
Then, I get the same error as before...

Have you actually tried that commandline? or do I have a strange version? (Just downloaded it last week)

Install-AzSKOrganizationPolicy : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ Install-AzSKOrganizationPolicy -SubscriptionId 097edece-e071-4747-a27 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Install-AzSKOrganizationPolicy], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Install-AzSKOrganizationPolicy

**Comment by VishalHaibatpure** [comment]
The given parameter set works for me with version 3.5.0
Make sure you are **not** using "_-DepartmentName_" in your command. That is the only parameter not supported for custom resources setup for Org policy. 

If this is not helping out, you can try executing command using PowerShell ISE command window

![image](https://user-images.githubusercontent.com/28297899/44402572-e2cf7600-a56f-11e8-9bb5-336de00a2530.png)

**Comment by Stoffe** [comment]
Ahh, ok, didnt know the DepartmentName was not suppose to be on, ok, however now I get another error...

`
InvalidArgument: Only alphanumeric characters are supported in StorageAccountName param. And length should be less than 24 characters 
`

And, I tried to have 1 letter, 3 letters, 10 letters and one number in the storageaccount name, and even tried to remove characters from other parameters to a minimum to make sure the error message is relevant...

**Comment by VishalHaibatpure** [comment]
It should work with **unique** alphanumeric name as storage account names are scoped globally across subscriptions.

**Comment by njohnso** [comment]
Found a solution to @Stoffe problem.  In case others have the same issue.  If you receive the error:

 `InvalidArgument: Only alphanumeric characters are supported in StorageAccountName param. And length should be less than 24 characters`

You are using uppercase letters.  Use all lowercase letters and this will work fine. Suggested a solution here:

https://github.com/azsk/DevOpsKit/issues/966
