### ISSUE TITLE
Support for Azure Government

### ISSUE THREAD

**Issue by KevinDMack** [azsk/DevOpsKit#202]
This would be a variable valuable tool for government customers but when I attempt to run it and even try to set the -Environment I received a "the provided account ... does not have access to subscription ID ..." which is inline with an error trying to execute against a commercial endpoint.

**Comment by VishalHaibatpure** [comment]
@KevinDMack : AzSK internally uses AzureRM commands to evaluate controls. 
You can check if subscription is getting listed on executing below AzureRM PowerShell command. 

```PowerShell
Get-AzureRmSubscription
```

**Comment by VishalHaibatpure** [comment]
@KevinDMack : latest AzSK version-3.8.0 (manual and CICD scans) works in sovereign clouds. Please give a try and let us know your feedback.
