### ISSUE TITLE
Standardize Indentation using spaces

### ISSUE THREAD

**Issue by DexterPOSH** [azsk/DevOpsKit#205]
## Description</br>
The code is using a mix and match of spaces and tabs at the moment for indenting code.
This is a sore to eye while reading the code, can this be standardized to only using spaces (1tab=4spaces)?

## Steps to reproduce
Open the *.ps1 files from the source code in VSCode (or any other editor) and you'd notice that there.
![image](https://user-images.githubusercontent.com/6275375/44699017-e72fed80-aa9f-11e8-9799-d3c2ccdedc09.png)

## Expected behavior</br> 
Standardized indentation using whitespaces instead of tabs.

## Actual behavior</br>
Mix & match of tab & whitespace for indentation.

**Comment by Khushboo-msft** [comment]
@DexterPOSH Thanks for the pointer. We'll definitely add this to our backlog.
