### ISSUE TITLE
Install-AzSKOMSSolution shows only results of baseline controls in Log Analytics

### ISSUE THREAD

**Issue by GuruCharan94** [azsk/DevOpsKit#206]
## Title</br>
Install-AzSKOMSSolution shows only results of baseline controls in Log Analytics
## Description</br>

https://github.com/azsk/DevOpsKit/blob/cdf5daff6c6ff9e305c9f2642d8bbc625da2cbac/src/AzSK/Framework/Configurations/AlertMonitoring/AZSK.AM.OMS.GenericView.V2.omsview#L100

The key filter being **IsBaselineControl_b == true** 
Can the OMS View take additional parameters for this?
## Steps to reproduce

Run Subscription Scan after setting up AzSK OMS Solution
```PowerShell

```
## Expected behavior</br> 
Log Analytics should show same number of results as csv files generated.

## Actual behavior</br>
Log Analytics shows only Baseline Controls

**Comment by GuruCharan94** [comment]
I can also contribute with a PR if needed. Let me know

**Comment by Khushboo-msft** [comment]
@GuruCharan94 The AzSK Monitoring solution adds blades to the Log Analytics workspace based on the queries that we think the users might find useful.
You can always modify the queries associated with the views (blades) as per your requirement.
Refer [this ](https://github.com/azsk/DevOpsKit-docs/blob/master/05-Alerting-and-Monitoring/Readme.md#next-steps)for details.

Hope that helps!

**Comment by GuruCharan94** [comment]
Great. Thanks for clarifying that this is the expected behavior.
