### ISSUE TITLE
Azure_AppService_DP_Dont_Allow_HTTP_Access_Fn not reporting a valid state

### ISSUE THREAD

**Issue by stephaneey** [azsk/DevOpsKit#295]
## Description</br>
When running a subscription scan, the control Azure_AppService_DP_Dont_Allow_HTTP_Access_Fn reports functions as "passed" although SSL is not enforced.
## Steps to reproduce

```PowerShell
Get-AzSKAzureServicesSecurityStatus
```
## Expected behavior</br> 
I assume that the function apps which do not have HTTPS enforced should be reported as failed.

## Actual behavior</br>
Function Apps allowing both HTTP & HTTPS are listed as "passed" for the above control.

**Comment by Akreddy123** [comment]
We have just checked that control and it gave the expected results. 
Go to your functionapp -> Platform features -> SSL -> Bindings
and check whether HTTPS Only is turned on or off.

**Comment by stephaneey** [comment]
Hello,

Thanks for your answer. That's what I did, HTTPS Only is turned off...So if I understand correctly, for a "passed" result, it should be turned on right?

Best Regards

**Comment by Akreddy123** [comment]
Yes, for a "passed" result, it should be turned on

**Comment by stephaneey** [comment]
It's not but, it is set to "Off" but shows "passed" in the result, that's why I logged this issue...but if you double-checked, there must be something wrong...I didn't make any attestation or custom policy or whatsoever

**Comment by Akreddy123** [comment]
If you have attested the control as Not an Issue, the result shows "passed" . There is another column named Actual result which shows "failed"

**Comment by stephaneey** [comment]
I just said in my previous comment that I haven't attested anything. I can give you resource details (subscription, function apps) etc. So, to repeat it completely:
- I simply run the Get-AzSKAzureServicesSecurityStatus over a subscription on a **fresh AzSK setup with no custom policy, no attestation**.
- I find in the returned report the following (see picture, names obfuscated purposely):
![azsk](https://user-images.githubusercontent.com/2558877/47557474-08cb1b00-d911-11e8-9e39-5d3106bd9c93.png)
but I suspected the function apps not to be configured properly so I manually checked in the portal and for all of them, Platform Features ==> SSL ==> Bindings ==> HTTPS Only is set to **Off**

In the screenshot, the only "correct" status in the one in error as indeed for some reason, this function app cannot be retrieved anymore from the portal or even from PowerShell but all the others marked as "passed" have their HTTPS Only flag set to OFF.

Hope it is clear!
Thanks

**Comment by Akreddy123** [comment]
Can you share the complete logs for this control

**Comment by stephaneey** [comment]
Yes but where, I don't want to disclose any details publicly. Basically, in my screenshot you have it all, if you need the resource identifiers, just give me a mail where I can send this info privately.

Thanks

**Comment by Akreddy123** [comment]
Send the details to akaleti@microsoft.com

thanks

**Comment by stephaneey** [comment]
Done :)

Thanks

**Comment by Akreddy123** [comment]
go to => https://{functionappname}.scm.azurewebsites.net/api/functions and check in the config whether the type="http triggered" . If not it will give you result as "passed".

sample config:
"config":{"bindings":[{"authLevel":"function","name":"req","type":"httpTrigger",

**Comment by stephaneey** [comment]
Ok that was it! Well seen and it makes sense...Didn't think of that one.

Thanks
