### ISSUE TITLE
Enforcing MSI at App Service level

### ISSUE THREAD

**Issue by stephaneey** [azsk/DevOpsKit#306]
## [feature request] Azure_AppService_AuthN_Use_Managed_Service_Identity
</br>

## Description</br>
As described by the below pointer, a few controls are available to enforce some behavior right from the ARM template. 
https://github.com/azsk/DevOpsKit-docs/blob/master/ARMTemplates/AppService.json
It'd be nice to be able to add the MSI check as well.
## Steps to reproduce
N/A

**Comment by VishalHaibatpure** [comment]
@stephaneey thanks for suggestion. We will add this in ARM checker. We already have backlog to add all compatible AzSK Controls to ARM checker.

**Comment by stephaneey** [comment]
Great!

**Comment by AjeetChouksey** [comment]
Hi, Is there any update on this.
