### ISSUE TITLE
Security IntelliSense

### ISSUE THREAD

**Issue by felickz** [azsk/DevOpsKit#39]
Any plans to release these as an Analyzer NuGet?  Open Source the code?

(ref: [SecurityIntelliSense-Preview](https://marketplace.visualstudio.com/items?itemName=AzSDKTeam.SecurityIntelliSense-Preview))

**Comment by sbyna-msft** [comment]
@felickz we shall open source the code soon. Last few months we were primarily focusing on open sourcing DevOpsKit core module source code. Converting this as analyzer nuget, is in our backlog. But our focus initially would be to open source the SecIntel code for outside contributions.
