### ISSUE TITLE
Migrate code and docs to "normal" GitHub orgs

### ISSUE THREAD

**Issue by nschonni** [azsk/DevOpsKit#399]
Using a separate organization and running on azurewebsites doesn't give users much confidence that this is an actual Microsoft project.
Do you have plans to migrate this under the https://github.com/Azure and https://github.com/MicrosoftDocs organizations?

**Comment by abhaydaga** [comment]
@nschonni : We are currently more focused on getting cloud security baseline compliance higher up. But, we are definitely exploring and looking into the migration process.
