### ISSUE TITLE
Get-AzSKARMTemplateSecurityStatus seems to fail under linux containers

### ISSUE THREAD

**Issue by avishnyakov** [azsk/DevOpsKit#488]
## Title
Get-AzSKARMTemplateSecurityStatus seems to fail under linux containers

## Description
Get-AzSKARMTemplateSecurityStatus seems to fail under linux containers

## Steps to reproduce
Run Get-AzSKARMTemplateSecurityStatus under any linux docker container. It fails on CSV file creation because of the path issues.  $Env:LOCALAPPDATA is null under Linux containers, and then the path does not get created at all. 

```
Export-Csv : Could not find a part of the path '/Microsoft/AzSKLogs/ARMChecker/20190325_061020/ARMCheckerResults_20190325_061020.csv'.
At /opt/microsoft/powershell/6/Modules/AzSK/3.11.0/Framework/Core/ARMChecker/ARMCheckerStatus.ps1:232 char:16
+ ...        $csvResults| Export-Csv $csvFilePath -NoTypeInformation -Force
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OpenError: (:) [Export-Csv], DirectoryNotFoundException
+ FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.ExportCsvCommand
```

```PowerShell
Name                           Value
----                           -----
PSVersion                      6.1.3
PSEdition                      Core
GitCommitId                    6.1.3
OS                             Linux 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
## Expected behavior</br> 
* It works
* Ideally, there is a docker container for this project

## Actual behavior</br>
It fails on path creation under linux container.

This is actually related to Enable Get-AzSKARMTemplateSecurityStatus to Output results to Array #267 issue raised by @PlagueHO. A very opinionated approach on creating CSV files with no way to specify path or disable it at all, or get the output array of result objects. Should we have an option to get an array as output, this problem partly go away.

The very challenge is integration with other tools:
* CI/CD scenarios
* broader analytic gathering across hundreds of applications and templates (we need to push output data into Splunk, AppInsights, etc but don't have this ability)
* making additional decisions on should we fail / pass the build
* other internal automation where we need to analyse output and trigger different rules (eg, notify security team on specific violations) 

I might help with this fix, looking into source code.

**Comment by RiniChandra** [comment]
Hi @avishnyakov ,
The DevOpsKit is not supported on Linux environment. You can find more about the prerequisites [here](https://github.com/azsk/DevOpsKit-docs/tree/master/00a-Setup#installation-guide) in our Installation guide.

**Comment by avishnyakov** [comment]
@RiniChandra why not? What are the dependencies? Can it be used in a Docker container? If not, why?

It would be nice if documentation covered this.
