### ISSUE TITLE
Non-interactively run Get-AzSKAzureDevOpsSecurityStatus

### ISSUE THREAD

**Issue by DoronNN** [azsk/DevOpsKit#531]
## Title</br>
Non-interactively run Get-AzSKAzureDevOpsSecurityStatus
## Description</br>
We want to be able to run this under a non user account, so that there's not interactive login needed. Is this something that can be placed on your backlog or anything?

## Steps to reproduce

```PowerShell
Get-AzSKAzureDevOpsSecurityStatus -OrganizationName <"Whatever"> -Credentials $credentialObject
```
## Expected behavior</br> 
User is logged in non-interactively.

## Actual behavior</br>
Does not exist

**Comment by SINIKI** [comment]
Hi @DoronNN, we are looking into this feature. You will see it soon. We will update this thread once the feature is ready for release.

**Comment by fleed** [comment]
I have the same issue. Would like to run the tool from an Azure Pipeline.
Any ETA?

**Comment by abhaydaga** [comment]
@fleed @DoronNN 

1. You can non interactively run scan commands by using PAT. Here is an example:

```PowerShell 
$token = '<Enter Your PAT>' 
$secureString = ConvertTo-SecureString $token -AsPlainText -Force

Get-AzSKAzureDevOpsSecurityStatus -OrganizationName <"Whatever"> -PATToken $secureString

Refer the list [here](https://github.com/azsk/DevOpsKit-docs/tree/master/09-AzureDevOps(VSTS)-Security/PATPrivileges) for customizing the PAT required for Azure DevOps Connection with minimum required privileges.

2.  To run the tool from pipeline, refer to our document [here](https://aka.ms/adoscanner)
