### ISSUE TITLE
Could not find a part of the path '/Microsoft/AzSK/AzSKSettings.json'

### ISSUE THREAD

**Issue by EvgeniaMartynova** [azsk/DevOpsKit#552]
## Title</br>
Could not find a part of the path '/Microsoft/AzSK/AzSKSettings.json'
## Description</br>
When executing any of AzSK commands under Ubuntu 14.04, 18.04 they fail with a reason:
Could not find a part of the path '/Microsoft/AzSK/AzSKSettings.json'
## Steps to reproduce
Execute 

```PowerShell
$PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.2.0
PSEdition                      Core
GitCommitId                    6.2.0
OS                             Linux 3.13.0-163-generic #213-Ubuntu SMP Thu Nov 15 02:19:07 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
Get-AzSKAzureServicesSecurityStatus <subscription_id>
```
## Expected behavior</br> 
The command execute successfully

## Actual behavior</br>
The commands gives an error: "Could not find a part of the path '/Microsoft/AzSK/AzSKSettings.json'" and does not execute till the end

**Comment by Khushboo-msft** [comment]
@EvgeniaMartynova AzSK is not supported on Linux OS. The [Installation Guide](https://github.com/azsk/DevOpsKit-docs/blob/master/00a-Setup/Readme.md#installation-guide) should help.
