### ISSUE TITLE
Install-AzSKContinuousAssurance fails when specifying a list of RG

### ISSUE THREAD

**Issue by EvgeniaMartynova** [azsk/DevOpsKit#554]
## Title</br>
Install-AzSKContinuousAssurance fails when specifying a list of RG
## Description</br>
Install-AzSKContinuousAssurance fails when specifying a comma separated list of resource groups as parameters
## Steps to reproduce

Execute _Install-AzSKContinuousAssurance_ command providing for _ResourceGroupNames_ parameter a comma separated list of resource groups
```PowerShell
Install-AzSKContinuousAssurance -SubscriptionId <SubscriptionId> `
	        -ResourceGroupNames <ResourceGroupName1>,  <ResourceGroupName1>`
	        -OMSWorkspaceId <WorkspaceId> `
	        -OMSSharedKey <SharedKey> 
```
## Expected behavior</br> 
The command executed successfully

## Actual behavior</br>
The command fails with the following error:

![rg-error](https://user-images.githubusercontent.com/50482694/57520335-ae7a3080-731d-11e9-8379-0c48b17abc6f.png)

**Comment by Khushboo-msft** [comment]
@EvgeniaMartynova Could you please check if you specified the comma separated list of resource groups inside single/double quotation marks ('<ResourceGroup1>,<ResourceGroup2>... ', or "<ResourceGroup1>,<ResourceGroup2>... ").

**Comment by EvgeniaMartynova** [comment]
@Khushboo-msft, indeed specifying the list of resource group names either in single or in double quotes fixes the problem. Thanks a lot.
Could the documentation at [https://github.com/azsk/DevOpsKit-docs/tree/master/04-Continous-Assurance](https://github.com/azsk/DevOpsKit-docs/tree/master/04-Continous-Assurance) please be updated saying explicitly the comma separated list should be in quotes?

**Comment by Khushboo-msft** [comment]
@EvgeniaMartynova Sure, we'll do that.
