### ISSUE TITLE
Incorrectly tagged code needs to be ignorable

### ISSUE THREAD

**Issue by BrianMinister** [azsk/DevOpsKit#652]
## Description</br>
I have discovered that game code, which needs to be secured now, with everything being online and with online transactions, 

The issue is that some code like `Random rng = new Random();` triggers an error. There needs to be a way to in code ignore that one line, otherwise these checks are useless for secured game development.

**Comment by v-soukum** [comment]
Can you provide some more details about the issue?
Is it related to the DevOps kit?

**Comment by BrianMinister** [comment]
That was from over a year ago. I don't remember enough to remember why I wrote that. Not good letting these comments get cold like this.
