### ISSUE TITLE
CA Multiple accounts setup with custom Org policy

### ISSUE THREAD

**Issue by EvgeniaMartynova** [azsk/DevOpsKit#712]
## Title</br>
CA Multiple accounts setup with custom Org policy
## Description</br>
CA Scan failing with the following error: 
Get-AzStorageAccount : Resource group 'AzSKRG' could not be found. At C:\Modules\User\AzSK\Framework\Core\SVT\SubscriptionCore\SubscriptionCore.ps1:1532 char:27 + ... rageAccount = Get-AzStorageAccount -ResourceGroupName $AzSKRG | Where ... + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : CloseError: (:) [Get-AzStorageAccount], CloudException + FullyQualifiedErrorId : Microsoft.Azure.Commands.Management.Storage.GetAzureStorageAccountCommand 
## Steps to reproduce
Setup multiple CA accounts following instructions here:
https://github.com/azsk/DevOpsKit-docs/tree/master/04-Continous-Assurance

```PowerShell

```
## Expected behavior</br> 
Scan completed successfully

## Actual behavior</br>
The error occurs during a scan execution:
Get-AzStorageAccount : Resource group 'AzSKRG' could not be found. At C:\Modules\User\AzSK\Framework\Core\SVT\SubscriptionCore\SubscriptionCore.ps1:1532 char:27 + ... rageAccount = Get-AzStorageAccount -ResourceGroupName $AzSKRG | Where ... + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : CloseError: (:) [Get-AzStorageAccount], CloudException + FullyQualifiedErrorId : Microsoft.Azure.Commands.Management.Storage.GetAzureStorageAccountCommand

**Comment by EvgeniaMartynova** [comment]
This seems to be a regression after upgrade to 3.15.0 version of AzSK.
With AzSK 3.12.0 the scans were running successfully.
Now no scans can be performed.

**Comment by SINIKI** [comment]
Hi @EvgeniaMartynova:

Can you share exact AzSK command which is throwing this error?

Use `Get-AzSKContinuousAssurance` command to check the status of continuous assurance account on your subscription. This command will verify CA setup on your subscription and will give appropriate recommendations to help fix the issue.

Full command: `Get-AzSKContinuousAssurance -SubscriptionId $SubId -ExhaustiveCheck`

If you are trying to install multiple continuous assurance account in a subscription, make sure you are using all the required parameter:
```
Install-AzSKContinuousAssurance -SubscriptionId $SubscriptionId -ResourceGroupNames $ResourceGroupNames -LAWSId $LAWSId -LAWSSharedKey $LAWSSharedKey 
        -AutomationAccountRGName $AutomationAccountRGName -AutomationAccountName $AutomationAccountName -AutomationAccountLocation $AutomationAccountLocation
```

**Comment by EvgeniaMartynova** [comment]
Hi SINIKI,

This issue can be closed - the issue is fixed by itself after a couple of scans.
