### ISSUE TITLE
Support version '2017-03-01-preview' for Microsoft.Sql/servers/securityAlertPolicies 

### ISSUE THREAD

**Issue by mikanyg** [azsk/DevOpsKit#741]
## Title</br>
Support version '2017-03-01-preview' for Microsoft.Sql/servers/securityAlertPolicies 

## Description</br>
When exporting templates from Azure Portal, the Microsoft.Sql/servers/securityAlertPolicies resource is exported using api version '2017-03-01-preview'. The json for this version is different than the one accepted by AzSK, which is based on api version '2015-05-01-preview'. Examples are that email adresses should be arrays in 2017 version and emailAccountAdmins is a true boolean type.

Any ARM Template  Check fails when using 2017 version.

## Steps to reproduce
Export a SQL Server Database template from Azure Portal and run ARM Template Check using AzSK.

## Expected behavior</br> 
'2017-03-01-preview' api version Microsoft.Sql/servers/securityAlertPolicies resources can be verified with ARM Template Checker.

## Actual behavior</br>
Currently only api version '2015-05-01-preview' will pass ARM Template Check.

**Comment by mikanyg** [comment]
I see some very weird behaviour for this control in ARM template check. Even when using the compliant ARM template for SQL Server, the ARM Template check fails due to expecting a boolean value for the emailAccountAdmins property. But the ARM Template showcases a string property with value 'Enabled', and doing an ARM deployment validation fails if this property is a boolean whenever the api version is 2015-05-01-preview.

And browsing the official docs I cannot find supprot for 2015: https://docs.microsoft.com/en-us/azure/templates/microsoft.sql/2015-05-01-preview/servers/securityalertpolicies
only 2017 api version seems official: https://docs.microsoft.com/en-us/azure/templates/microsoft.sql/2017-03-01-preview/servers/securityalertpolicies

**Comment by VincentLepape** [comment]
I have exactly the same problem.
Let me know when the issue will be fixed

The 2 rules below for the "securityAlertPolicies" seems not compatible with any API versions

`"jsonPath": [ "$.properties.emailAccountAdmins" ],
          "matchType": "Boolean",
          "data": { "value": true }`
+
`"jsonPath": [ "$.properties.emailAddresses" ],
          "matchType": "StringWhitespace",`

**Comment by mikanyg** [comment]
@VincentLepape did you also experience the same issue for the disabledAlerts property? I can see that the [matchType](https://github.com/azsk/DevOpsKit/blob/70191d5f5b955c301cc7465584079e42f9ef02ba/src/AzSK/Framework/Configurations/ARMChecker/ARMControls.json#L371) is the same as for emailAddresses but the official ARM template has it as a string array.

**Comment by mikanyg** [comment]
Another thing to note is that even though the failed results is being added to an exclusion file and the failures are correctly set to Skipped, the overall task is still failing. My guess is that its due to some internal exception during evalution of Microsoft.SqlServer resources. 

When I remove these resources from the template, but still have other resources with some failures added to exclusion file, the overall task succeeds as expected.

**Comment by mikanyg** [comment]
This seems to have been resolved in the latest AzSK 4.6.0 release. At least we are no longer getting failures from `Microsoft.Sql/servers/*`.
