### ISSUE TITLE
Least Privilege Service Principal/Permission Rights requirement to run AzSK

### ISSUE THREAD

**Issue by pag-r** [azsk/DevOpsKit#866]
## Title</br>
Least Privilege Service Principal/Permission Rights requirement to run AzSK
## Description</br>
I'm trying to find in a doc, but maybe I'm missing something. I would like to understand what is the least SP requirements to run all out-of-box checks.

**Comment by Garima-msft** [comment]
Refer [link ](https://github.com/azsk/DevOpsKit-docs/blob/ba4d6c46aa75d07c107620d1e81b7ac90e40a76e/00b-Getting-Started/Readme.md#complete-list-of-azsk-commands) to know about minimum access required to run a scan
Some controls require higher privileges (Owner/ Co-Admin) for scanning and will not get scanned via minimum permissions

**Comment by pag-r** [comment]
Thanks for info. I've missed it. It's good reference point.
